name: dailyglow
description: "A girly daily diary app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.0.0

  # State Management
  provider: ^6.1.2

  # UI & Fonts
  google_fonts: ^6.2.1

  # Utilities
  intl: ^0.19.0
  http: ^1.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # =========================
  # ASSETS (WAJIB BENAR)
  # =========================
  assets:
    - assets/images/
